/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PaginationProps {
  pages?: {
    /**
     * The URL to the page
     */
    url: string;
    /**
     * Indicates if the page is currently active
     */
    active?: boolean;
  }[];
}
