/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Variant of button to be used
 */
export type Variant = "primary" | "secondary" | "tertiary";
export type RequiredCookies = {
  /**
   * The name of the required cookie
   */
  name?: string;
  /**
   * A description of the required cookie
   */
  description?: string;
}[];

export interface CookieConsentProps {
  notice?: InitialCookieConsentNotice;
  dialogue?: CookieConsentDialogue;
}
/**
 * The initial notice displayed to users regarding cookie consent.
 */
export interface InitialCookieConsentNotice {
  /**
   * The display mode of the cookie consent component
   */
  displayMode?: "card" | "banner";
  /**
   * The title of the cookie consent section
   */
  title?: string;
  acceptButton?: {
    /**
     * The label for the accept button
     */
    label?: string;
  };
  rejectButton?: {
    /**
     * The label for the reject button
     */
    label?: string;
  };
  customizeButton?: {
    /**
     * The label for the customize button
     */
    label?: string;
    variant?: Variant;
  };
  decisionButtonVariant?: Variant;
  /**
   * The description of the cookie consent section
   */
  description?: string;
}
/**
 * The dialogue displayed when users choose to customize their cookie preferences.
 */
export interface CookieConsentDialogue {
  /**
   * The title of the cookie consent dialogue
   */
  title?: string;
  /**
   * The description of the cookie consent dialogue
   */
  description?: string;
  required?: RequiredCookies;
  buttons?: {
    /**
     * The label for the accept button in the dialogue
     */
    acceptLabel?: string;
    /**
     * The label for the reject button in the dialogue
     */
    rejectLabel?: string;
    /**
     * The label for the button to save preferences
     */
    savePreferencesLabel?: string;
  };
  /**
   * The variant of the decision buttons in the dialogue
   */
  decisionButtonVariant?: "secondary" | "tertiary";
  options?: {
    /**
     * The name of the cookie category
     */
    name?: string;
    /**
     * A description of the cookie category
     */
    description?: string;
    /**
     * Whether the cookie category is checked by default
     */
    checked?: boolean;
  }[];
  toggleLabels?: {
    /**
     * Label for enabled toggle state
     */
    accept?: string;
    /**
     * Label for disabled toggle state
     */
    reject?: string;
  };
}
