/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Date of the appointment
 */
export type Date = string;
/**
 * Time of the appointment
 */
export type Time = string;
/**
 * Label for the call to action button
 */
export type CTALabel = string;

export interface EventListAppointmentProps {
  date?: Date;
  time?: Time;
  label?: CTALabel;
}
