/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BreadcrumbProps {
  /**
   * An array of breadcrumb pages. Each page should have a URL and a label.
   */
  pages?: {
    /**
     * The URL to the page
     */
    url: string;
    /**
     * The label for the title of the page
     */
    label: string;
  }[];
}
