/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {CtaProps} from "../cta/CtaProps";
import type {DividerProps} from "../divider/DividerProps";
import type {FaqProps} from "../faq/FaqProps";
import type {FeaturesProps} from "../features/FeaturesProps";
import type {GalleryProps} from "../gallery/GalleryProps";
import type {HeroProps} from "../hero/HeroProps";
import type {HtmlProps} from "../html/HtmlProps";
import type {ImageStoryProps} from "../image-story/ImageStoryProps";
import type {ImageTextProps} from "../image-text/ImageTextProps";
import type {LogosProps} from "../logos/LogosProps";
import type {MosaicProps} from "../mosaic/MosaicProps";
import type {SliderProps} from "../slider/SliderProps";
import type {StatsProps} from "../stats/StatsProps";
import type {TeaserCardProps} from "../teaser-card/TeaserCardProps";
import type {TestimonialsProps} from "../testimonials/TestimonialsProps";
import type {TextProps} from "../text/TextProps";
import type {VideoCurtainProps} from "../video-curtain/VideoCurtainProps";

/**
 * Sets the minimum width for each half of the split layout
 */
export type ContentMinimumWidth = "narrow" | "medium" | "wide";
/**
 * Sets the space between the content inside the two halves of the split layout
 */
export type ContentGutter = "narrow" | "default" | "wide" | "none";
/**
 * Determines the layout of the sections on mobile devices
 */
export type MobileLayout = "stack" | "stackReverse";
/**
 * Aligns the content vertically within the sections
 */
export type VerticalAlignment = "top" | "center" | "bottom";
/**
 * Sets the vertical space between the content of the split layout
 */
export type VerticalGutter = "large" | "default" | "small" | "none";
/**
 * Sets the horizontal space between the content of the split layout
 */
export type HorizontalGutter = "large" | "default" | "small" | "none";
/**
 * Allowed components for the first half of the split layout
 */
export type First = (
  | CtaProps
  | DividerProps
  | FaqProps
  | FeaturesProps
  | GalleryProps
  | HeroProps
  | HtmlProps
  | ImageStoryProps
  | ImageTextProps
  | LogosProps
  | MosaicProps
  | SliderProps
  | StatsProps
  | TeaserCardProps
  | TestimonialsProps
  | TextProps
  | VideoCurtainProps
)[];
/**
 * Allowed components for the second half of the split layout
 */
export type Second = (
  | CtaProps
  | DividerProps
  | FaqProps
  | FeaturesProps
  | GalleryProps
  | HeroProps
  | HtmlProps
  | ImageStoryProps
  | ImageTextProps
  | LogosProps
  | MosaicProps
  | SliderProps
  | StatsProps
  | TeaserCardProps
  | TestimonialsProps
  | TextProps
  | VideoCurtainProps
)[];

export interface SplitEvenProps {
  contentMinWidth?: ContentMinimumWidth;
  contentGutter?: ContentGutter;
  mobileLayout?: MobileLayout;
  verticalAlign?: VerticalAlignment;
  verticalGutter?: VerticalGutter;
  horizontalGutter?: HorizontalGutter;
  firstComponents?: First;
  secondComponents?: Second;
}
