/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Title of the event
 */
export type EventTitle = string;
/**
 * Label of the category
 */
export type Label = string;
/**
 * Categories to which the event belongs
 */
export type Categories = {
  label?: Label;
}[];
/**
 * Short intro text for the event
 */
export type Intro = string;
/**
 * Date of the appointment
 */
export type Date = string;
/**
 * Time of the appointment
 */
export type Time = string;
/**
 * Label for the call to action button
 */
export type CTALabel = string;
/**
 * List of dates of the event
 */
export type Dates = {
  date?: Date;
  time?: Time;
  label?: CTALabel;
  [k: string]: unknown;
}[];
/**
 * Address of the appointment
 */
export type Address = string;
/**
 * Link to the location on a map
 */
export type MapsLink = string;
/**
 * List of attendable appointments
 */
export type Appointments = {
  dates?: Dates;
  address: Address;
  mapsLink?: MapsLink;
}[];
/**
 * Description of the event
 */
export type Description = string;
/**
 * Image source to use
 */
export type ImageSource = string;
/**
 * Image description
 */
export type AltText = string;
/**
 * Images displayed below the text content
 */
export type Images = {
  src?: ImageSource;
  alt?: AltText;
}[];

export interface EventProps {
  title?: EventTitle;
  categories?: Categories;
  intro?: Intro;
  appointments?: Appointments;
  description?: Description;
  images?: Images;
}
