/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Title of the event
 */
export type Headline = string;
/**
 * Short teaser text for the event
 */
export type Text = string;
/**
 * The date of the event
 */
export type Date = string;
/**
 * The time of the event
 */
export type Time = string;
/**
 * Name of the location
 */
export type LocationName = string;
/**
 * Address of the location
 */
export type Address = string;
/**
 * Categories of the event
 */
export type Categories = string[];
/**
 * URL of the image to display
 */
export type ImageSource = string;
/**
 * Alt text of the image
 */
export type AltText = string;
/**
 * The event entry URL to link
 */
export type URL = string;
/**
 * Text for the call to action
 */
export type CallToAction = string;
/**
 * ARIA label for accessibility
 */
export type ARIALabel = string;

/**
 * Display an event teaser with date, title and location
 */
export interface EventListTeaserProps {
  title: Headline;
  text?: Text;
  date: Date;
  time?: Time;
  location: Location;
  categories?: Categories;
  image?: Image;
  url?: URL;
  cta?: CallToAction;
  ariaLabel?: ARIALabel;
  className?: string;
}
/**
 * Location of the event
 */
export interface Location {
  name?: LocationName;
  address?: Address;
}
/**
 * Image to display in the teaser
 */
export interface Image {
  src?: ImageSource;
  alt?: AltText;
}
