/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {EventListAppointmentProps} from "../event-list-appointment/EventListAppointmentProps";

/**
 * Title of the event
 */
export type EventTitle = string;
/**
 * Label of the category
 */
export type Label = string;
/**
 * Categories to which the event belongs
 */
export type Categories = {
  label?: Label;
}[];
/**
 * Short intro text for the event
 */
export type Intro = string;
/**
 * List of attendable appointments
 */
export type Appointments = EventListAppointmentProps[];
/**
 * Description of the event
 */
export type Description = string;
/**
 * Image source to use
 */
export type ImageSource = string;
/**
 * Image description
 */
export type AltText = string;
/**
 * Images displayed below the text content
 */
export type Images = {
  src?: ImageSource;
  alt?: AltText;
}[];

export interface EventDetailProps {
  title?: EventTitle;
  categories?: Categories;
  intro?: Intro;
  appointments?: Appointments;
  description?: Description;
  images?: Images;
}
