/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {EventFilterProps} from "../event-filter/EventFilterProps";

export interface EventListProps {
  /**
   * Referenced component EventFilterProps
   */
  filter?: EventFilterProps;
}
