/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {SearchFilterProps} from "../search-filter/SearchFilterProps";
import type {SearchResultProps} from "../search-result/SearchResultProps";

export interface SearchProps {
  /**
   * Referenced component SearchFilterProps
   */
  searchFilter?: SearchFilterProps;
  searchResults?: SearchResultProps[];
}
