/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {EventTeaserProps} from "../event-teaser/EventTeaserProps";

/**
 * Headline for the listing
 */
export type Headline = string;
/**
 * Additional text shown below the headline
 */
export type Text = string;
/**
 * List of events to display
 *
 * @minItems 1
 */
export type Events = [EventTeaserProps, ...EventTeaserProps[]];
/**
 * The to link
 */
export type URL = string;
/**
 * The text for the link
 */
export type Text1 = string;

/**
 * Display a list of latest events, ordered chronologically
 */
export interface EventLatestProps {
  headline?: Headline;
  text?: Text;
  events?: Events;
  link?: Link;
  className?: string;
}
/**
 * Link shown below the listing
 */
export interface Link {
  url: URL;
  text?: Text1;
}
