/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The label for the element
 */
export type Label = string;
export type Options = OptionSelectButton[];

/**
 * Component used for user interaction
 */
export interface SelectionRackProps {
  options?: Options;
  value?: string;
}
/**
 * An option in the selection rack
 */
export interface OptionSelectButton {
  label: Label;
  value?: string;
}
