/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {EventListAppointmentProps} from "../event-list-appointment/EventListAppointmentProps";

/**
 * List of dates of the event
 */
export type Dates = EventListAppointmentProps[];
/**
 * Name of the event location
 */
export type LocationName = string;
/**
 * Address of the appointment
 */
export type Address = string;
/**
 * Links related to the event location
 */
export type Links = {
  href: string;
  label: string;
  /**
   * Open link in a new tab
   */
  newTab?: boolean;
}[];

export interface EventListLocationProps {
  dates?: Dates;
  locationName?: LocationName;
  address?: Address;
  links?: Links;
}
