/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {EventListAppointmentProps} from "../event-list-appointment/EventListAppointmentProps";

/**
 * List of dates of the event
 */
export type Dates = EventListAppointmentProps[];
/**
 * Address of the appointment
 */
export type Address = string;
/**
 * Link to the location on a map
 */
export type MapsLink = string;

export interface EventListLocationProps {
  dates?: Dates;
  address?: Address;
  mapsLink?: MapsLink;
}
