/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sets the minimum width for each section in the split layout
 */
export type SectionMinimumWidth = "narrow" | "medium" | "wide";
/**
 * Determines the layout of the sections on mobile devices
 */
export type MobileLayout = "stack" | "stackReverse";
/**
 * Enable sticky positioning for the sections
 */
export type Sticky = boolean;
/**
 * Aligns the content vertically within the sections
 */
export type VerticalAlignment = "top" | "center" | "bottom";
/**
 * The space between the two sections
 */
export type Gutter = "large" | "default" | "small" | "none";

export interface SplitEvenProps {
  sectionMinWidth?: SectionMinimumWidth;
  mobileLayout?: MobileLayout;
  sticky?: Sticky;
  verticalAlign?: VerticalAlignment;
  gutter?: Gutter;
}
