/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The date of the event
 */
export type Date = string;
/**
 * Title of the event
 */
export type Headline = string;
/**
 * Location of the event
 */
export type Location = string;
/**
 * The event entry URL to link
 */
export type URL = string;
/**
 * The text for the link
 */
export type Text = string;

/**
 * Display an event teaser with date, headline and location
 */
export interface EventTeaserProps {
  date: Date;
  headline: Headline;
  location: Location;
  link?: Link;
  className?: string;
}
/**
 * URL and label for the event linked
 */
export interface Link {
  url: URL;
  text?: Text;
}
